- hosts: google_cloud
  become: yes
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes

    - name: Install necessary libraries
      apt:
        name:
          - libnl-genl-3-dev
          - libkeyutils-dev
          - bison
          - flex
        state: present

    - name: Remove old lustre client modules
      apt:
        name: lustre-client-modules-5.4.0-96-generic
        state: absent

    - name: Install new lustre client modules
      apt:
        deb: /home/ext_kazuki_fujii_rio_gsic_titech/scripts/lustre-client-modules-5.15.0-1008-gcp-tcpx_2.15.62-22-gf2868d1-1_amd64.deb

    - name: Load lustre module
      modprobe:
        name: lustre
        state: present

    - name: Create mount directory
      file:
        path: /lustre
        state: directory

    - name: Mount lustre filesystem
      mount:
        path: /lustre
        src: 172.16.0.29:/lustre
        fstype: lustre
        opts: defaults
        state: mounted
